### ISSUE TITLE
beef up unit-tests, add more function

### ISSUE THREAD

**Issue by chetmurthy** [domsj/orocksdb#13]
I'd like to beef up the unit-tests, add support to orocksdb for things like snapshots, etc.  Is this something you'd like to merge into your repo, or should I fork?

Also, thank you for doing this work -- it's very nice.  I would have used camlidl, and that would have been interminable.

**Comment by domsj** [comment]
Better tests are long overdue, so that would surely be welcome.
Any other functionality (such as snapshots) is welcome too, I just haven't added it because so far we didn't need it.

Nice to know you like the binding :-), have fun building your application with it!
