### ISSUE TITLE
Hacking together an ocaml-rocksdb interface based on the C++ API

### ISSUE THREAD

**Issue by chetmurthy** [domsj/orocksdb#24]
Hi, I've been using orocksdb for a while, and needed access to more of the functions.  In this case, specifically access to column-families, but I anticipate needing access to a lot more.  Ctypes was ... looking daunting, and esp. b/c the RocksDB C API calls for the stuff i wanted to access involved a lot of memory-management.  Seemed painful.  But on the other hand, the C++ APIs were very clean, b/c they were done in the Google C++ style, and using STL containers.  To make a long story short, I decided to write an "IDL compiler" against the C++ API, and it seems to have worked out really nicely.

https://github.com/chetmurthy/ocaml-cppffigen
https://github.com/chetmurthy/ocaml-rocksdb

I thought I'd show it  to you because you might find it something you wish to adopt.  Obviously I can completely understand why you might want to continue on the path you've already chosen, but I figured, it would only be collegial/friendly/polite to ask.

Please feel free to contact me at chetsky at gmail dot com if you'd like to discuss privately.

And of course, if you're at all interested in this tool, I'm happy to discuss changes you think would be useful.

**Comment by domsj** [comment]
Hi @chetmurthy,
Thanks for letting me know. The cpp ffi gen approach is definitely interesting.
For now I'm happy with what orocksdb does, so I won't be switching just yet ;-). If your binding picks up some more steam, and if I need more rocksdb functionality, I might consider it though - less maintenance on my end is always a good thing.
If I need to bind another c++ library from ocaml I'll definitely have an in depth look at what you've created.

Best of luck with your new projects.
Kind regards, Jan
